### ISSUE TITLE
Add single and bulk "delete" feature to all list tables

### ISSUE THREAD

**Issue by mtsalenc** [FeeSimple/data-manager#13]

**Comment by trungtt1981** [comment]
It's also needed to delete the property.
So, in the view of property editing, add a "delete" button top-right onClick, the current property will be deleted. Before deletion, a "confirmation" dialog will show up.

**Comment by trungtt1981** [comment]
Done at commit:

https://github.com/FeeSimple/data-manager/commit/e0a5f22f36d271655491abf1ea84ca83485b6b63
