### ISSUE TITLE
Sq ft invalid entry error preventing saving units

### ISSUE THREAD

**Issue by jasonlynx** [FeeSimple/data-manager#61]
Getting an invalid entry error for sq ft even though sq ft max is more than sq ft min.

<img width="1242" alt="Screen Shot 2019-05-09 at 9 00 12 AM" src="https://user-images.githubusercontent.com/15249825/57455543-5669fe00-7239-11e9-9799-8ba4b4a01784.png">

**Comment by trungtt1981** [comment]
Fixed
